<p style="color:#824AE8;font-family:Ubuntu Light;font-size:140%">DATA SCIENCE IN CHEMISTRY</p>

# Automating Chemical Data Retrieval with PubChemPy

In [1]:
import pubchempy as pcp

In [2]:
molecules = ['methane',
             '2-acetyloxybenzoic acid',
             'pentanal', 
             'aspirin', 
             'ibuprofen', 
             'paracetamol', 
             'naproxen', 
             'diclofenac', 
             'codeine',
             'ethanol',
             'methamphetamine',
             'morphine', 
             'caprolactam',
             'Amygdalin',
             'Fenfuram',
             'citral',
             'Zearalenone',
             'Picene',
             "2,2',4,6,6'-Pentachlorobiphenyl", 
             'Estradiol', 
             'Dieldrin', 
             'Rotenone',
             'Sulfaclozine',
             'ethanal',
             '2-pyrrolidone', 
             '2-Chloronaphthalene',
             'Primidone',
             '2-Chloropropane',
             'Doxylamine',
             '6,7-Dihydropteridine',
             'Benzonitrile',
             'Diazinon',
             'Acetorphine hydrochloride',
             'Diethyl Ether',
             '5-Hydroxytryptophan',
             'Warfarin',
             'Atropine',
             'Chloramphenicol',
             'Lansoprazole',
             'Acetorphine',
             '3-Chloroalanine',
             'Methylnaltrexone',
             'Buprenorphine',
             'Nalorphine',
             ]

In [3]:
len(molecules)

44

___________________________________

## 1. Automate Getting SDF of a list of Molecules

In [4]:
pcp.download("SDF", "aspirin.sdf", "aspirin", "name")

In [6]:
import os

newfolder = input("Create a New Folder for your Molecules:")
if not os.path.exists(newfolder):
    os.makedirs(newfolder, exist_ok=True)
    print(f"Folder created: {newfolder}")
else:
    print(f"Folder already exists: {newfolder}")

Create a New Folder for your Molecules:PubChem Molecules
Folder created: PubChem Molecules

In [7]:
for name in molecules:
    pcp.download("SDF", f"./{newfolder}/{name}.sdf", name, "name")

In [9]:
pcp.get_sdf("aspirin", "name")

'2244\n  -OEChem-08222417162D\n\n 21 21  0     0  0  0  0  0  0999 V2000\n    3.7320   -0.0600    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n    6.3301    1.4400    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n    4.5981    1.4400    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n    2.8660   -1.5600    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n    4.5981   -0.5600    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    5.4641   -0.0600    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    4.5981   -1.5600    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    6.3301   -0.5600    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    5.4641   -2.0600    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    6.3301   -1.5600    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    5.4641    0.9400    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    2.8660   -0.5600    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    2.0000   -0.0600    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    4.0611   -1.8700    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0\n    6.8671   -0.2500    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0\n    5.4641   -2.6800    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0\n    6.8671   -1.8700    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0\n    2.3100    0.4769    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0\n    1.4631    0.2500    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0\n    1.6900   -0.5969    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0\n    6.3301    2.0600    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0\n  1  5  1  0  0  0  0\n  1 12  1  0  0  0  0\n  2 11  1  0  0  0  0\n  2 21  1  0  0  0  0\n  3 11  2  0  0  0  0\n  4 12  2  0  0  0  0\n  5  6  1  0  0  0  0\n  5  7  2  0  0  0  0\n  6  8  2  0  0  0  0\n  6 11  1  0  0  0  0\n  7  9  1  0  0  0  0\n  7 14  1  0  0  0  0\n  8 10  1  0  0  0  0\n  8 15  1  0  0  0  0\n  9 10  2  0  0  0  0\n  9 16  1  0  0  0  0\n 10 17  1  0  0  0  0\n 12 13  1  0  0  0  0\n 13 18  1  0  0  0  0\n 13 19  1  0  0  0  0\n 13 20  1  0  0  0  0\nM  END\n> <PUBCHEM_COMPOUND_CID>\n2244\n\n> <PUBCHEM_COMPOUND_CANONICALIZED>\n1\n\n> <PUBCHEM_CACTVS_COMPLEXITY>\n212\n\n> <PUBCHEM_CACTVS_HBOND_ACCEPTOR>\n4\n\n> <PUBCHEM_CACTVS_HBOND_DONOR>\n1\n\n> <PUBCHEM_CACTVS_ROTATABLE_BOND>\n3\n\n> <PUBCHEM_CACTVS_SUBSKEYS>\nAAADccBwOAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAABAAAAGgAACAAADASAmAAyDoAABgCIAiDSCAACCAAkIAAIiAEGCMgMJzaENRqCe2Cl4BEIuYeIyCCOAAAAAAAIAAAAAAAAABAAAAAAAAAAAA==\n\n> <PUBCHEM_IUPAC_OPENEYE_NAME>\n2-acetoxybenzoic acid\n\n> <PUBCHEM_IUPAC_CAS_NAME>\n2-acetyloxybenzoic acid\n\n> <PUBCHEM_IUPAC_NAME_MARKUP>\n2-acetyloxybenzoic acid\n\n> <PUBCHEM_IUPAC_NAME>\n2-acetyloxybenzoic acid\n\n> <PUBCHEM_IUPAC_SYSTEMATIC_NAME>\n2-acetyloxybenzoic acid\n\n> <PUBCHEM_IUPAC_TRADITIONAL_NAME>\n2-acetoxybenzoic acid\n\n> <PUBCHEM_IUPAC_INCHI>\nInChI=1S/C9H8O4/c1-6(10)13-8-5-3-2-4-7(8)9(11)12/h2-5H,1H3,(H,11,12)\n\n> <PUBCHEM_IUPAC_INCHIKEY>\nBSYNRYMUTXBXSQ-UHFFFAOYSA-N\n\n> <PUBCHEM_XLOGP3>\n1.2\n\n> <PUBCHEM_EXACT_MASS>\n180.04225873\n\n> <PUBCHEM_MOLECULAR_FORMULA>\nC9H8O4\n\n> <PUBCHEM_MOLECULAR_WEIGHT>\n180.16\n\n> <PUBCHEM_OPENEYE_CAN_SMILES>\nCC(=O)OC1=CC=CC=C1C(=O)O\n\n> <PUBCHEM_OPENEYE_ISO_SMILES>\nCC(=O)OC1=CC=CC=C1C(=O)O\n\n> <PUBCHEM_CACTVS_TPSA>\n63.6\n\n> <PUBCHEM_MONOISOTOPIC_WEIGHT>\n180.04225873\n\n> <PUBCHEM_TOTAL_CHARGE>\n0\n\n> <PUBCHEM_HEAVY_ATOM_COUNT>\n13\n\n> <PUBCHEM_ATOM_DEF_STEREO_COUNT>\n0\n\n> <PUBCHEM_ATOM_UDEF_STEREO_COUNT>\n0\n\n> <PUBCHEM_BOND_DEF_STEREO_COUNT>\n0\n\n> <PUBCHEM_BOND_UDEF_STEREO_COUNT>\n0\n\n> <PUBCHEM_ISOTOPIC_ATOM_COUNT>\n0\n\n> <PUBCHEM_COMPONENT_COUNT>\n1\n\n> <PUBCHEM_CACTVS_TAUTO_COUNT>\n-1\n\n> <PUBCHEM_COORDINATE_TYPE>\n1\n5\n255\n\n> <PUBCHEM_BONDANNOTATIONS>\n5  6  8\n5  7  8\n6  8  8\n7  9  8\n8  10  8\n9  10  8\n\n$$$$\n'

In [10]:
def make_sdf(molecules):
    """
    molecules : a list of molecules
    """
    sdfs = []
    
    for name in molecules:
        cmpd_sdf = pcp.get_sdf(name, "name")
        sdfs.append(cmpd_sdf)
        
    with open("pubchem_molecules.sdf", "w") as f:
        f.write("".join(sdfs))
    print("DONE.")    

make_sdf(molecules)

DONE.

________________________________________________

## 2. Creating a Database for a list of Molecules

In [11]:
data = []
for name in molecules:
    compound = pcp.get_compounds(name, "name")[0]
    data.append({
        "Name": name,
        "CID": compound.cid,
        "IUPAC_Name": compound.iupac_name,
        "Molecular_Formula": compound.molecular_formula,
        "Molecular_Weight": compound.molecular_weight,
        "SMILES": compound.isomeric_smiles,
        "InChI": compound.inchi,
        "InChIKey": compound.inchikey
    })

data

[{'Name': 'methane',
  'CID': 297,
  'IUPAC_Name': 'methane',
  'Molecular_Formula': 'CH4',
  'Molecular_Weight': '16.043',
  'SMILES': 'C',
  'InChI': 'InChI=1S/CH4/h1H4',
  'InChIKey': 'VNWKTOKETHGBQD-UHFFFAOYSA-N'},
 {'Name': '2-acetyloxybenzoic acid',
  'CID': 2244,
  'IUPAC_Name': '2-acetyloxybenzoic acid',
  'Molecular_Formula': 'C9H8O4',
  'Molecular_Weight': '180.16',
  'SMILES': 'CC(=O)OC1=CC=CC=C1C(=O)O',
  'InChI': 'InChI=1S/C9H8O4/c1-6(10)13-8-5-3-2-4-7(8)9(11)12/h2-5H,1H3,(H,11,12)',
  'InChIKey': 'BSYNRYMUTXBXSQ-UHFFFAOYSA-N'},
 {'Name': 'pentanal',
  'CID': 8063,
  'IUPAC_Name': 'pentanal',
  'Molecular_Formula': 'C5H10O',
  'Molecular_Weight': '86.13',
  'SMILES': 'CCCCC=O',
  'InChI': 'InChI=1S/C5H10O/c1-2-3-4-5-6/h5H,2-4H2,1H3',
  'InChIKey': 'HGBOYTHUEUWSSQ-UHFFFAOYSA-N'},
 {'Name': 'aspirin',
  'CID': 2244,
  'IUPAC_Name': '2-acetyloxybenzoic acid',
  'Molecular_Formula': 'C9H8O4',
  'Molecular_Weight': '180.16',
  'SMILES': 'CC(=O)OC1=CC=CC=C1C(=O)O',
  'InChI': 'InChI=1S/C9H8O4/c1-6(10)13-8-5-3-2-4-7(8)9(11)12/h2-5H,1H3,(H,11,12)',
  'InChIKey': 'BSYNRYMUTXBXSQ-UHFFFAOYSA-N'},
 {'Name': 'ibuprofen',
  'CID': 3672,
  'IUPAC_Name': '2-[4-(2-methylpropyl)phenyl]propanoic acid',
  'Molecular_Formula': 'C13H18O2',
  'Molecular_Weight': '206.28',
  'SMILES': 'CC(C)CC1=CC=C(C=C1)C(C)C(=O)O',
  'InChI': 'InChI=1S/C13H18O2/c1-9(2)8-11-4-6-12(7-5-11)10(3)13(14)15/h4-7,9-10H,8H2,1-3H3,(H,14,15)',
  'InChIKey': 'HEFNNWSXXWATRW-UHFFFAOYSA-N'},
 {'Name': 'paracetamol',
  'CID': 1983,
  'IUPAC_Name': 'N-(4-hydroxyphenyl)acetamide',
  'Molecular_Formula': 'C8H9NO2',
  'Molecular_Weight': '151.16',
  'SMILES': 'CC(=O)NC1=CC=C(C=C1)O',
  'InChI': 'InChI=1S/C8H9NO2/c1-6(10)9-7-2-4-8(11)5-3-7/h2-5,11H,1H3,(H,9,10)',
  'InChIKey': 'RZVAJINKPMORJF-UHFFFAOYSA-N'},
 {'Name': 'naproxen',
  'CID': 156391,
  'IUPAC_Name': '(2S)-2-(6-methoxynaphthalen-2-yl)propanoic acid',
  'Molecular_Formula': 'C14H14O3',
  'Molecular_Weight': '230.26',
  'SMILES': 'C[C@@H](C1=CC2=C(C=C1)C=C(C=C2)OC)C(=O)O',
  'InChI': 'InChI=1S/C14H14O3/c1-9(14(15)16)10-3-4-12-8-13(17-2)6-5-11(12)7-10/h3-9H,1-2H3,(H,15,16)/t9-/m0/s1',
  'InChIKey': 'CMWTZPSULFXXJA-VIFPVBQESA-N'},
 {'Name': 'diclofenac',
  'CID': 3033,
  'IUPAC_Name': '2-[2-(2,6-dichloroanilino)phenyl]acetic acid',
  'Molecular_Formula': 'C14H11Cl2NO2',
  'Molecular_Weight': '296.1',
  'SMILES': 'C1=CC=C(C(=C1)CC(=O)O)NC2=C(C=CC=C2Cl)Cl',
  'InChI': 'InChI=1S/C14H11Cl2NO2/c15-10-5-3-6-11(16)14(10)17-12-7-2-1-4-9(12)8-13(18)19/h1-7,17H,8H2,(H,18,19)',
  'InChIKey': 'DCOPUUMXTXDBNB-UHFFFAOYSA-N'},
 {'Name': 'codeine',
  'CID': 5284371,
  'IUPAC_Name': '(4R,4aR,7S,7aR,12bS)-9-methoxy-3-methyl-2,4,4a,7,7a,13-hexahydro-1H-4,12-methanobenzofuro[3,2-e]isoquinolin-7-ol',
  'Molecular_Formula': 'C18H21NO3',
  'Molecular_Weight': '299.4',
  'SMILES': 'CN1CC[C@]23[C@@H]4[C@H]1CC5=C2C(=C(C=C5)OC)O[C@H]3[C@H](C=C4)O',
  'InChI': 'InChI=1S/C18H21NO3/c1-19-8-7-18-11-4-5-13(20)17(18)22-16-14(21-2)6-3-10(15(16)18)9-12(11)19/h3-6,11-13,17,20H,7-9H2,1-2H3/t11-,12+,13-,17-,18-/m0/s1',
  'InChIKey': 'OROGSEYTTFOCAN-DNJOTXNNSA-N'},
 {'Name': 'ethanol',
  'CID': 702,
  'IUPAC_Name': 'ethanol',
  'Molecular_Formula': 'C2H6O',
  'Molecular_Weight': '46.07',
  'SMILES': 'CCO',
  'InChI': 'InChI=1S/C2H6O/c1-2-3/h3H,2H2,1H3',
  'InChIKey': 'LFQSCWFLJHTTHZ-UHFFFAOYSA-N'},
 {'Name': 'methamphetamine',
  'CID': 10836,
  'IUPAC_Name': '(2S)-N-methyl-1-phenylpropan-2-amine',
  'Molecular_Formula': 'C10H15N',
  'Molecular_Weight': '149.23',
  'SMILES': 'C[C@@H](CC1=CC=CC=C1)NC',
  'InChI': 'InChI=1S/C10H15N/c1-9(11-2)8-10-6-4-3-5-7-10/h3-7,9,11H,8H2,1-2H3/t9-/m0/s1',
  'InChIKey': 'MYWUZJCMWCOHBA-VIFPVBQESA-N'},
 {'Name': 'morphine',
  'CID': 5288826,
  'IUPAC_Name': '(4R,4aR,7S,7aR,12bS)-3-methyl-2,4,4a,7,7a,13-hexahydro-1H-4,12-methanobenzofuro[3,2-e]isoquinoline-7,9-diol',
  'Molecular_Formula': 'C17H19NO3',
  'Molecular_Weight': '285.34',
  'SMILES': 'CN1CC[C@]23[C@@H]4[C@H]1CC5=C2C(=C(C=C5)O)O[C@H]3[C@H](C=C4)O',
  'InChI': 'InChI=1S/C17H19NO3/c1-18-7-6-17-10-3-5-13(20)16(17)21-15-12(19)4-2-9(14(15)17)8-11(10)18/h2-5,10-11,13,16,19-20H,6-8H2,1H3/t10-,11+,13-,16-,17-/m0/s1',
  'InChIKey': 'BQJCRHHNABKAKU-KBQPJGBKSA-N'},
 {'Name': 'caprolactam',
  'CID': 7768,
  'IUPAC_Name': 'azepan-2-one',
  'Molecular_Formula': 'C6H11NO',
  'Molecular_Weight': '113.16',
  'SMILES': 'C1CCC(=O)NCC1',
  'InChI': 'InChI=1S/C6H11NO/c8-6-4-2-1-3-5-7-6/h1-5H2,(H,7,8)',
  'InChIKey': 'JBKVHLHDHHXQEQ-UHFFFAOYSA-N'},
 {'Name': 'Amygdalin',
  'CID': 656516,
  'IUPAC_Name': '(2R)-2-phenyl-2-[(2R,3R,4S,5S,6R)-3,4,5-trihydroxy-6-[[(2R,3R,4S,5S,6R)-3,4,5-trihydroxy-6-(hydroxymethyl)oxan-2-yl]oxymethyl]oxan-2-yl]oxyacetonitrile',
  'Molecular_Formula': 'C20H27NO11',
  'Molecular_Weight': '457.4',
  'SMILES': 'C1=CC=C(C=C1)[C@H](C#N)O[C@H]2[C@@H]([C@H]([C@@H]([C@H](O2)CO[C@H]3[C@@H]([C@H]([C@@H]([C@H](O3)CO)O)O)O)O)O)O',
  'InChI': 'InChI=1S/C20H27NO11/c21-6-10(9-4-2-1-3-5-9)30-20-18(28)16(26)14(24)12(32-20)8-29-19-17(27)15(25)13(23)11(7-22)31-19/h1-5,10-20,22-28H,7-8H2/t10-,11+,12+,13+,14+,15-,16-,17+,18+,19+,20+/m0/s1',
  'InChIKey': 'XUCIJNAGGSZNQT-JHSLDZJXSA-N'},
 {'Name': 'Fenfuram',
  'CID': 90590,
  'IUPAC_Name': '2-methyl-N-phenylfuran-3-carboxamide',
  'Molecular_Formula': 'C12H11NO2',
  'Molecular_Weight': '201.22',
  'SMILES': 'CC1=C(C=CO1)C(=O)NC2=CC=CC=C2',
  'InChI': 'InChI=1S/C12H11NO2/c1-9-11(7-8-15-9)12(14)13-10-5-3-2-4-6-10/h2-8H,1H3,(H,13,14)',
  'InChIKey': 'JFSPBVWPKOEZCB-UHFFFAOYSA-N'},
 {'Name': 'citral',
  'CID': 638011,
  'IUPAC_Name': '(2E)-3,7-dimethylocta-2,6-dienal',
  'Molecular_Formula': 'C10H16O',
  'Molecular_Weight': '152.23',
  'SMILES': 'CC(=CCC/C(=C/C=O)/C)C',
  'InChI': 'InChI=1S/C10H16O/c1-9(2)5-4-6-10(3)7-8-11/h5,7-8H,4,6H2,1-3H3/b10-7+',
  'InChIKey': 'WTEVQBCEXWBHNA-JXMROGBWSA-N'},
 {'Name': 'Zearalenone',
  'CID': 5281576,
  'IUPAC_Name': '(4S,12E)-16,18-dihydroxy-4-methyl-3-oxabicyclo[12.4.0]octadeca-1(14),12,15,17-tetraene-2,8-dione',
  'Molecular_Formula': 'C18H22O5',
  'Molecular_Weight': '318.4',
  'SMILES': 'C[C@H]1CCCC(=O)CCC/C=C/C2=C(C(=CC(=C2)O)O)C(=O)O1',
  'InChI': 'InChI=1S/C18H22O5/c1-12-6-5-9-14(19)8-4-2-3-7-13-10-15(20)11-16(21)17(13)18(22)23-12/h3,7,10-12,20-21H,2,4-6,8-9H2,1H3/b7-3+/t12-/m0/s1',
  'InChIKey': 'MBMQEIFVQACCCH-QBODLPLBSA-N'},
 {'Name': 'Picene',
  'CID': 9162,
  'IUPAC_Name': 'picene',
  'Molecular_Formula': 'C22H14',
  'Molecular_Weight': '278.3',
  'SMILES': 'C1=CC=C2C(=C1)C=CC3=C2C=CC4=C3C=CC5=CC=CC=C54',
  'InChI': 'InChI=1S/C22H14/c1-3-7-17-15(5-1)9-11-21-19(17)13-14-20-18-8-4-2-6-16(18)10-12-22(20)21/h1-14H',
  'InChIKey': 'GBROPGWFBFCKAG-UHFFFAOYSA-N'},
 {'Name': "2,2',4,6,6'-Pentachlorobiphenyl",
  'CID': 91662,
  'IUPAC_Name': '1,3,5-trichloro-2-(2,6-dichlorophenyl)benzene',
  'Molecular_Formula': 'C12H5Cl5',
  'Molecular_Weight': '326.4',
  'SMILES': 'C1=CC(=C(C(=C1)Cl)C2=C(C=C(C=C2Cl)Cl)Cl)Cl',
  'InChI': 'InChI=1S/C12H5Cl5/c13-6-4-9(16)12(10(17)5-6)11-7(14)2-1-3-8(11)15/h1-5H',
  'InChIKey': 'MTCPZNVSDFCBBE-UHFFFAOYSA-N'},
 {'Name': 'Estradiol',
  'CID': 5757,
  'IUPAC_Name': '(8R,9S,13S,14S,17S)-13-methyl-6,7,8,9,11,12,14,15,16,17-decahydrocyclopenta[a]phenanthrene-3,17-diol',
  'Molecular_Formula': 'C18H24O2',
  'Molecular_Weight': '272.4',
  'SMILES': 'C[C@]12CC[C@H]3[C@H]([C@@H]1CC[C@@H]2O)CCC4=C3C=CC(=C4)O',
  'InChI': 'InChI=1S/C18H24O2/c1-18-9-8-14-13-5-3-12(19)10-11(13)2-4-15(14)16(18)6-7-17(18)20/h3,5,10,14-17,19-20H,2,4,6-9H2,1H3/t14-,15-,16+,17+,18+/m1/s1',
  'InChIKey': 'VOXZDWNPVJITMN-ZBRFXRBCSA-N'},
 {'Name': 'Dieldrin',
  'CID': 969491,
  'IUPAC_Name': '(1R,2S,3S,6R,7R,8S,9S,11R)-3,4,5,6,13,13-hexachloro-10-oxapentacyclo[6.3.1.13,6.02,7.09,11]tridec-4-ene',
  'Molecular_Formula': 'C12H8Cl6O',
  'Molecular_Weight': '380.9',
  'SMILES': 'C1[C@@H]2[C@H]3[C@@H]([C@H]1[C@H]4[C@@H]2O4)[C@]5(C(=C([C@@]3(C5(Cl)Cl)Cl)Cl)Cl)Cl',
  'InChI': 'InChI=1S/C12H8Cl6O/c13-8-9(14)11(16)5-3-1-2(6-7(3)19-6)4(5)10(8,15)12(11,17)18/h2-7H,1H2/t2-,3+,4+,5-,6-,7+,10+,11-',
  'InChIKey': 'DFBKLUNHFCTMDC-PICURKEMSA-N'},
 {'Name': 'Rotenone',
  'CID': 6758,
  'IUPAC_Name': '(1S,6R,13S)-16,17-dimethoxy-6-prop-1-en-2-yl-2,7,20-trioxapentacyclo[11.8.0.03,11.04,8.014,19]henicosa-3(11),4(8),9,14,16,18-hexaen-12-one',
  'Molecular_Formula': 'C23H22O6',
  'Molecular_Weight': '394.4',
  'SMILES': 'CC(=C)[C@H]1CC2=C(O1)C=CC3=C2O[C@@H]4COC5=CC(=C(C=C5[C@@H]4C3=O)OC)OC',
  'InChI': 'InChI=1S/C23H22O6/c1-11(2)16-8-14-15(28-16)6-5-12-22(24)21-13-7-18(25-3)19(26-4)9-17(13)27-10-20(21)29-23(12)14/h5-7,9,16,20-21H,1,8,10H2,2-4H3/t16-,20-,21+/m1/s1',
  'InChIKey': 'JUVIOZPCNVVQFO-HBGVWJBISA-N'},
 {'Name': 'Sulfaclozine',
  'CID': 66890,
  'IUPAC_Name': '4-amino-N-(6-chloropyrazin-2-yl)benzenesulfonamide',
  'Molecular_Formula': 'C10H9ClN4O2S',
  'Molecular_Weight': '284.72',
  'SMILES': 'C1=CC(=CC=C1N)S(=O)(=O)NC2=CN=CC(=N2)Cl',
  'InChI': 'InChI=1S/C10H9ClN4O2S/c11-9-5-13-6-10(14-9)15-18(16,17)8-3-1-7(12)2-4-8/h1-6H,12H2,(H,14,15)',
  'InChIKey': 'QKLPUVXBJHRFQZ-UHFFFAOYSA-N'},
 {'Name': 'ethanal',
  'CID': 177,
  'IUPAC_Name': 'acetaldehyde',
  'Molecular_Formula': 'C2H4O',
  'Molecular_Weight': '44.05',
  'SMILES': 'CC=O',
  'InChI': 'InChI=1S/C2H4O/c1-2-3/h2H,1H3',
  'InChIKey': 'IKHGUXGNUITLKF-UHFFFAOYSA-N'},
 {'Name': '2-pyrrolidone',
  'CID': 12025,
  'IUPAC_Name': 'pyrrolidin-2-one',
  'Molecular_Formula': 'C4H7NO',
  'Molecular_Weight': '85.10',
  'SMILES': 'C1CC(=O)NC1',
  'InChI': 'InChI=1S/C4H7NO/c6-4-2-1-3-5-4/h1-3H2,(H,5,6)',
  'InChIKey': 'HNJBEVLQSNELDL-UHFFFAOYSA-N'},
 {'Name': '2-Chloronaphthalene',
  'CID': 7056,
  'IUPAC_Name': '2-chloronaphthalene',
  'Molecular_Formula': 'C10H7Cl',
  'Molecular_Weight': '162.61',
  'SMILES': 'C1=CC=C2C=C(C=CC2=C1)Cl',
  'InChI': 'InChI=1S/C10H7Cl/c11-10-6-5-8-3-1-2-4-9(8)7-10/h1-7H',
  'InChIKey': 'CGYGETOMCSJHJU-UHFFFAOYSA-N'},
 {'Name': 'Primidone',
  'CID': 4909,
  'IUPAC_Name': '5-ethyl-5-phenyl-1,3-diazinane-4,6-dione',
  'Molecular_Formula': 'C12H14N2O2',
  'Molecular_Weight': '218.25',
  'SMILES': 'CCC1(C(=O)NCNC1=O)C2=CC=CC=C2',
  'InChI': 'InChI=1S/C12H14N2O2/c1-2-12(9-6-4-3-5-7-9)10(15)13-8-14-11(12)16/h3-7H,2,8H2,1H3,(H,13,15)(H,14,16)',
  'InChIKey': 'DQMZLTXERSFNPB-UHFFFAOYSA-N'},
 {'Name': '2-Chloropropane',
  'CID': 6361,
  'IUPAC_Name': '2-chloropropane',
  'Molecular_Formula': 'C3H7Cl',
  'Molecular_Weight': '78.54',
  'SMILES': 'CC(C)Cl',
  'InChI': 'InChI=1S/C3H7Cl/c1-3(2)4/h3H,1-2H3',
  'InChIKey': 'ULYZAYCEDJDHCC-UHFFFAOYSA-N'},
 {'Name': 'Doxylamine',
  'CID': 3162,
  'IUPAC_Name': 'N,N-dimethyl-2-(1-phenyl-1-pyridin-2-ylethoxy)ethanamine',
  'Molecular_Formula': 'C17H22N2O',
  'Molecular_Weight': '270.37',
  'SMILES': 'CC(C1=CC=CC=C1)(C2=CC=CC=N2)OCCN(C)C',
  'InChI': 'InChI=1S/C17H22N2O/c1-17(20-14-13-19(2)3,15-9-5-4-6-10-15)16-11-7-8-12-18-16/h4-12H,13-14H2,1-3H3',
  'InChIKey': 'HCFDWZZGGLSKEP-UHFFFAOYSA-N'},
 {'Name': '6,7-Dihydropteridine',
  'CID': 167,
  'IUPAC_Name': '6,7-dihydropteridine',
  'Molecular_Formula': 'C6H6N4',
  'Molecular_Weight': '134.14',
  'SMILES': 'C1CN=C2C(=N1)C=NC=N2',
  'InChI': 'InChI=1S/C6H6N4/c1-2-9-6-5(8-1)3-7-4-10-6/h3-4H,1-2H2',
  'InChIKey': 'KVDQMARGGBLIJM-UHFFFAOYSA-N'},
 {'Name': 'Benzonitrile',
  'CID': 7505,
  'IUPAC_Name': 'benzonitrile',
  'Molecular_Formula': 'C7H5N',
  'Molecular_Weight': '103.12',
  'SMILES': 'C1=CC=C(C=C1)C#N',
  'InChI': 'InChI=1S/C7H5N/c8-6-7-4-2-1-3-5-7/h1-5H',
  'InChIKey': 'JFDZBHWFFUWGJE-UHFFFAOYSA-N'},
 {'Name': 'Diazinon',
  'CID': 3017,
  'IUPAC_Name': 'diethoxy-(6-methyl-2-propan-2-ylpyrimidin-4-yl)oxy-sulfanylidene-lambda5-phosphane',
  'Molecular_Formula': 'C12H21N2O3PS',
  'Molecular_Weight': '304.35',
  'SMILES': 'CCOP(=S)(OCC)OC1=NC(=NC(=C1)C)C(C)C',
  'InChI': 'InChI=1S/C12H21N2O3PS/c1-6-15-18(19,16-7-2)17-11-8-10(5)13-12(14-11)9(3)4/h8-9H,6-7H2,1-5H3',
  'InChIKey': 'FHIVAFMUCKRCQO-UHFFFAOYSA-N'},
 {'Name': 'Acetorphine hydrochloride',
  'CID': 71587068,
  'IUPAC_Name': '[(1R,2S,6R,14R,15R,19R)-19-[(2R)-2-hydroxypentan-2-yl]-15-methoxy-5-methyl-13-oxa-5-azahexacyclo[13.2.2.12,8.01,6.02,14.012,20]icosa-8(20),9,11,16-tetraen-11-yl] acetate;hydrochloride',
  'Molecular_Formula': 'C27H36ClNO5',
  'Molecular_Weight': '490.0',
  'SMILES': 'CCC[C@](C)([C@H]1C[C@@]23C=C[C@@]1([C@H]4[C@@]25CCN([C@@H]3CC6=C5C(=C(C=C6)OC(=O)C)O4)C)OC)O.Cl',
  'InChI': 'InChI=1S/C27H35NO5.ClH/c1-6-9-24(3,30)19-15-25-10-11-27(19,31-5)23-26(25)12-13-28(4)20(25)14-17-7-8-18(32-16(2)29)22(33-23)21(17)26;/h7-8,10-11,19-20,23,30H,6,9,12-15H2,1-5H3;1H/t19-,20-,23-,24-,25-,26+,27-;/m1./s1',
  'InChIKey': 'NDKZQFXDYCJPKG-PXCSINNHSA-N'},
 {'Name': 'Diethyl Ether',
  'CID': 3283,
  'IUPAC_Name': 'ethoxyethane',
  'Molecular_Formula': 'C4H10O',
  'Molecular_Weight': '74.12',
  'SMILES': 'CCOCC',
  'InChI': 'InChI=1S/C4H10O/c1-3-5-4-2/h3-4H2,1-2H3',
  'InChIKey': 'RTZKZFJDLAIYFH-UHFFFAOYSA-N'},
 {'Name': '5-Hydroxytryptophan',
  'CID': 144,
  'IUPAC_Name': '2-amino-3-(5-hydroxy-1H-indol-3-yl)propanoic acid',
  'Molecular_Formula': 'C11H12N2O3',
  'Molecular_Weight': '220.22',
  'SMILES': 'C1=CC2=C(C=C1O)C(=CN2)CC(C(=O)O)N',
  'InChI': 'InChI=1S/C11H12N2O3/c12-9(11(15)16)3-6-5-13-10-2-1-7(14)4-8(6)10/h1-2,4-5,9,13-14H,3,12H2,(H,15,16)',
  'InChIKey': 'LDCYZAJDBXYCGN-UHFFFAOYSA-N'},
 {'Name': 'Warfarin',
  'CID': 54678486,
  'IUPAC_Name': '4-hydroxy-3-(3-oxo-1-phenylbutyl)chromen-2-one',
  'Molecular_Formula': 'C19H16O4',
  'Molecular_Weight': '308.3',
  'SMILES': 'CC(=O)CC(C1=CC=CC=C1)C2=C(C3=CC=CC=C3OC2=O)O',
  'InChI': 'InChI=1S/C19H16O4/c1-12(20)11-15(13-7-3-2-4-8-13)17-18(21)14-9-5-6-10-16(14)23-19(17)22/h2-10,15,21H,11H2,1H3',
  'InChIKey': 'PJVWKTKQMONHTI-UHFFFAOYSA-N'},
 {'Name': 'Atropine',
  'CID': 174174,
  'IUPAC_Name': '[(1R,5S)-8-methyl-8-azabicyclo[3.2.1]octan-3-yl] 3-hydroxy-2-phenylpropanoate',
  'Molecular_Formula': 'C17H23NO3',
  'Molecular_Weight': '289.4',
  'SMILES': 'CN1[C@@H]2CC[C@H]1CC(C2)OC(=O)C(CO)C3=CC=CC=C3',
  'InChI': 'InChI=1S/C17H23NO3/c1-18-13-7-8-14(18)10-15(9-13)21-17(20)16(11-19)12-5-3-2-4-6-12/h2-6,13-16,19H,7-11H2,1H3/t13-,14+,15?,16?',
  'InChIKey': 'RKUNBYITZUJHSG-PJPHBNEVSA-N'},
 {'Name': 'Chloramphenicol',
  'CID': 5959,
  'IUPAC_Name': '2,2-dichloro-N-[(1R,2R)-1,3-dihydroxy-1-(4-nitrophenyl)propan-2-yl]acetamide',
  'Molecular_Formula': 'C11H12Cl2N2O5',
  'Molecular_Weight': '323.13',
  'SMILES': 'C1=CC(=CC=C1[C@H]([C@@H](CO)NC(=O)C(Cl)Cl)O)[N+](=O)[O-]',
  'InChI': 'InChI=1S/C11H12Cl2N2O5/c12-10(13)11(18)14-8(5-16)9(17)6-1-3-7(4-2-6)15(19)20/h1-4,8-10,16-17H,5H2,(H,14,18)/t8-,9-/m1/s1',
  'InChIKey': 'WIIZWVCIJKGZOK-RKDXNWHRSA-N'},
 {'Name': 'Lansoprazole',
  'CID': 3883,
  'IUPAC_Name': '2-[[3-methyl-4-(2,2,2-trifluoroethoxy)pyridin-2-yl]methylsulfinyl]-1H-benzimidazole',
  'Molecular_Formula': 'C16H14F3N3O2S',
  'Molecular_Weight': '369.4',
  'SMILES': 'CC1=C(C=CN=C1CS(=O)C2=NC3=CC=CC=C3N2)OCC(F)(F)F',
  'InChI': 'InChI=1S/C16H14F3N3O2S/c1-10-13(20-7-6-14(10)24-9-16(17,18)19)8-25(23)15-21-11-4-2-3-5-12(11)22-15/h2-7H,8-9H2,1H3,(H,21,22)',
  'InChIKey': 'MJIHNNLFOKEZEW-UHFFFAOYSA-N'},
 {'Name': 'Acetorphine',
  'CID': 20055090,
  'IUPAC_Name': '[(1R,2S,6R,14R,15R,19R)-19-[(2R)-2-hydroxypentan-2-yl]-15-methoxy-5-methyl-13-oxa-5-azahexacyclo[13.2.2.12,8.01,6.02,14.012,20]icosa-8(20),9,11,16-tetraen-11-yl] acetate',
  'Molecular_Formula': 'C27H35NO5',
  'Molecular_Weight': '453.6',
  'SMILES': 'CCC[C@](C)([C@H]1C[C@@]23C=C[C@@]1([C@H]4[C@@]25CCN([C@@H]3CC6=C5C(=C(C=C6)OC(=O)C)O4)C)OC)O',
  'InChI': 'InChI=1S/C27H35NO5/c1-6-9-24(3,30)19-15-25-10-11-27(19,31-5)23-26(25)12-13-28(4)20(25)14-17-7-8-18(32-16(2)29)22(33-23)21(17)26/h7-8,10-11,19-20,23,30H,6,9,12-15H2,1-5H3/t19-,20-,23-,24-,25-,26+,27-/m1/s1',
  'InChIKey': 'LFYBMMHFJIAKFE-PMEKXCSPSA-N'},
 {'Name': '3-Chloroalanine',
  'CID': 78,
  'IUPAC_Name': '2-amino-3-chloropropanoic acid',
  'Molecular_Formula': 'C3H6ClNO2',
  'Molecular_Weight': '123.54',
  'SMILES': 'C(C(C(=O)O)N)Cl',
  'InChI': 'InChI=1S/C3H6ClNO2/c4-1-2(5)3(6)7/h2H,1,5H2,(H,6,7)',
  'InChIKey': 'ASBJGPTTYPEMLP-UHFFFAOYSA-N'},
 {'Name': 'Methylnaltrexone',
  'CID': 5361918,
  'IUPAC_Name': '(4R,4aS,7aR,12bS)-3-(cyclopropylmethyl)-4a,9-dihydroxy-3-methyl-2,4,5,6,7a,13-hexahydro-1H-4,12-methanobenzofuro[3,2-e]isoquinolin-3-ium-7-one',
  'Molecular_Formula': 'C21H26NO4+',
  'Molecular_Weight': '356.4',
  'SMILES': 'C[N+]1(CC[C@]23[C@@H]4C(=O)CC[C@]2([C@H]1CC5=C3C(=C(C=C5)O)O4)O)CC6CC6',
  'InChI': 'InChI=1S/C21H25NO4/c1-22(11-12-2-3-12)9-8-20-17-13-4-5-14(23)18(17)26-19(20)15(24)6-7-21(20,25)16(22)10-13/h4-5,12,16,19,25H,2-3,6-11H2,1H3/p+1/t16-,19+,20+,21-,22?/m1/s1',
  'InChIKey': 'JVLBPIPGETUEET-GAAHOAFPSA-O'},
 {'Name': 'Buprenorphine',
  'CID': 644073,
  'IUPAC_Name': '(1S,2S,6R,14R,15R,16R)-5-(cyclopropylmethyl)-16-[(2S)-2-hydroxy-3,3-dimethylbutan-2-yl]-15-methoxy-13-oxa-5-azahexacyclo[13.2.2.12,8.01,6.02,14.012,20]icosa-8(20),9,11-trien-11-ol',
  'Molecular_Formula': 'C29H41NO4',
  'Molecular_Weight': '467.6',
  'SMILES': 'C[C@]([C@H]1C[C@@]23CC[C@@]1([C@H]4[C@@]25CCN([C@@H]3CC6=C5C(=C(C=C6)O)O4)CC7CC7)OC)(C(C)(C)C)O',
  'InChI': 'InChI=1S/C29H41NO4/c1-25(2,3)26(4,32)20-15-27-10-11-29(20,33-5)24-28(27)12-13-30(16-17-6-7-17)21(27)14-18-8-9-19(31)23(34-24)22(18)28/h8-9,17,20-21,24,31-32H,6-7,10-16H2,1-5H3/t20-,21-,24-,26+,27-,28+,29-/m1/s1',
  'InChIKey': 'RMRJXGBAOAMLHD-IHFGGWKQSA-N'},
 {'Name': 'Nalorphine',
  'CID': 5284595,
  'IUPAC_Name': '(4R,4aR,7S,7aR,12bS)-3-prop-2-enyl-2,4,4a,7,7a,13-hexahydro-1H-4,12-methanobenzofuro[3,2-e]isoquinoline-7,9-diol',
  'Molecular_Formula': 'C19H21NO3',
  'Molecular_Weight': '311.4',
  'SMILES': 'C=CCN1CC[C@]23[C@@H]4[C@H]1CC5=C2C(=C(C=C5)O)O[C@H]3[C@H](C=C4)O',
  'InChI': 'InChI=1S/C19H21NO3/c1-2-8-20-9-7-19-12-4-6-15(22)18(19)23-17-14(21)5-3-11(16(17)19)10-13(12)20/h2-6,12-13,15,18,21-22H,1,7-10H2/t12-,13+,15-,18-,19-/m0/s1',
  'InChIKey': 'UIQMVEYFGZJHCZ-SSTWWWIQSA-N'}]

In [12]:
import pandas as pd

df = pd.DataFrame(data)
df

,Name,CID,IUPAC_Name,Molecular_Formula,Molecular_Weight,SMILES,InChI,InChIKey
0,methane,297,methane,CH4,16.043,C,InChI=1S/CH4/h1H4,VNWKTOKETHGBQD-UHFFFAOYSA-N
1,2-acetyloxybenzoic acid,2244,2-acetyloxybenzoic acid,C9H8O4,180.16,CC(=O)OC1=CC=CC=C1C(=O)O,InChI=1S/C9H8O4/c1-6(10)13-8-5-3-2-4-7(8)9(11)...,BSYNRYMUTXBXSQ-UHFFFAOYSA-N
2,pentanal,8063,pentanal,C5H10O,86.13,CCCCC=O,"InChI=1S/C5H10O/c1-2-3-4-5-6/h5H,2-4H2,1H3",HGBOYTHUEUWSSQ-UHFFFAOYSA-N
3,aspirin,2244,2-acetyloxybenzoic acid,C9H8O4,180.16,CC(=O)OC1=CC=CC=C1C(=O)O,InChI=1S/C9H8O4/c1-6(10)13-8-5-3-2-4-7(8)9(11)...,BSYNRYMUTXBXSQ-UHFFFAOYSA-N
4,ibuprofen,3672,2-[4-(2-methylpropyl)phenyl]propanoic acid,C13H18O2,206.28,CC(C)CC1=CC=C(C=C1)C(C)C(=O)O,InChI=1S/C13H18O2/c1-9(2)8-11-4-6-12(7-5-11)10...,HEFNNWSXXWATRW-UHFFFAOYSA-N
5,paracetamol,1983,N-(4-hydroxyphenyl)acetamide,C8H9NO2,151.16,CC(=O)NC1=CC=C(C=C1)O,InChI=1S/C8H9NO2/c1-6(10)9-7-2-4-8(11)5-3-7/h2...,RZVAJINKPMORJF-UHFFFAOYSA-N
6,naproxen,156391,(2S)-2-(6-methoxynaphthalen-2-yl)propanoic acid,C14H14O3,230.26,C[C@@H](C1=CC2=C(C=C1)C=C(C=C2)OC)C(=O)O,InChI=1S/C14H14O3/c1-9(14(15)16)10-3-4-12-8-13...,CMWTZPSULFXXJA-VIFPVBQESA-N
7,diclofenac,3033,"2-[2-(2,6-dichloroanilino)phenyl]acetic acid",C14H11Cl2NO2,296.1,C1=CC=C(C(=C1)CC(=O)O)NC2=C(C=CC=C2Cl)Cl,InChI=1S/C14H11Cl2NO2/c15-10-5-3-6-11(16)14(10...,DCOPUUMXTXDBNB-UHFFFAOYSA-N
8,codeine,5284371,"(4R,4aR,7S,7aR,12bS)-9-methoxy-3-methyl-2,4,4a...",C18H21NO3,299.4,CN1CC[C@]23[C@@H]4[C@H]1CC5=C2C(=C(C=C5)OC)O[C...,InChI=1S/C18H21NO3/c1-19-8-7-18-11-4-5-13(20)1...,OROGSEYTTFOCAN-DNJOTXNNSA-N
9,ethanol,702,ethanol,C2H6O,46.07,CCO,"InChI=1S/C2H6O/c1-2-3/h3H,2H2,1H3",LFQSCWFLJHTTHZ-UHFFFAOYSA-N
10,methamphetamine,10836,(2S)-N-methyl-1-phenylpropan-2-amine,C10H15N,149.23,C[C@@H](CC1=CC=CC=C1)NC,InChI=1S/C10H15N/c1-9(11-2)8-10-6-4-3-5-7-10/h...,MYWUZJCMWCOHBA-VIFPVBQESA-N
11,morphine,5288826,"(4R,4aR,7S,7aR,12bS)-3-methyl-2,4,4a,7,7a,13-h...",C17H19NO3,285.34,CN1CC[C@]23[C@@H]4[C@H]1CC5=C2C(=C(C=C5)O)O[C@...,InChI=1S/C17H19NO3/c1-18-7-6-17-10-3-5-13(20)1...,BQJCRHHNABKAKU-KBQPJGBKSA-N
12,caprolactam,7768,azepan-2-one,C6H11NO,113.16,C1CCC(=O)NCC1,"InChI=1S/C6H11NO/c8-6-4-2-1-3-5-7-6/h1-5H2,(H,...",JBKVHLHDHHXQEQ-UHFFFAOYSA-N
13,Amygdalin,656516,"(2R)-2-phenyl-2-[(2R,3R,4S,5S,6R)-3,4,5-trihyd...",C20H27NO11,457.4,C1=CC=C(C=C1)[C@H](C#N)O[C@H]2[C@@H]([C@H]([C@...,InChI=1S/C20H27NO11/c21-6-10(9-4-2-1-3-5-9)30-...,XUCIJNAGGSZNQT-JHSLDZJXSA-N
14,Fenfuram,90590,2-methyl-N-phenylfuran-3-carboxamide,C12H11NO2,201.22,CC1=C(C=CO1)C(=O)NC2=CC=CC=C2,InChI=1S/C12H11NO2/c1-9-11(7-8-15-9)12(14)13-1...,JFSPBVWPKOEZCB-UHFFFAOYSA-N
15,citral,638011,"(2E)-3,7-dimethylocta-2,6-dienal",C10H16O,152.23,CC(=CCC/C(=C/C=O)/C)C,"InChI=1S/C10H16O/c1-9(2)5-4-6-10(3)7-8-11/h5,7...",WTEVQBCEXWBHNA-JXMROGBWSA-N
16,Zearalenone,5281576,"(4S,12E)-16,18-dihydroxy-4-methyl-3-oxabicyclo...",C18H22O5,318.4,C[C@H]1CCCC(=O)CCC/C=C/C2=C(C(=CC(=C2)O)O)C(=O)O1,InChI=1S/C18H22O5/c1-12-6-5-9-14(19)8-4-2-3-7-...,MBMQEIFVQACCCH-QBODLPLBSA-N
17,Picene,9162,picene,C22H14,278.3,C1=CC=C2C(=C1)C=CC3=C2C=CC4=C3C=CC5=CC=CC=C54,InChI=1S/C22H14/c1-3-7-17-15(5-1)9-11-21-19(17...,GBROPGWFBFCKAG-UHFFFAOYSA-N
18,"2,2',4,6,6'-Pentachlorobiphenyl",91662,"1,3,5-trichloro-2-(2,6-dichlorophenyl)benzene",C12H5Cl5,326.4,C1=CC(=C(C(=C1)Cl)C2=C(C=C(C=C2Cl)Cl)Cl)Cl,InChI=1S/C12H5Cl5/c13-6-4-9(16)12(10(17)5-6)11...,MTCPZNVSDFCBBE-UHFFFAOYSA-N
19,Estradiol,5757,"(8R,9S,13S,14S,17S)-13-methyl-6,7,8,9,11,12,14...",C18H24O2,272.4,C[C@]12CC[C@H]3[C@H]([C@@H]1CC[C@@H]2O)CCC4=C3...,InChI=1S/C18H24O2/c1-18-9-8-14-13-5-3-12(19)10...,VOXZDWNPVJITMN-ZBRFXRBCSA-N
20,Dieldrin,969491,"(1R,2S,3S,6R,7R,8S,9S,11R)-3,4,5,6,13,13-hexac...",C12H8Cl6O,380.9,C1[C@@H]2[C@H]3[C@@H]([C@H]1[C@H]4[C@@H]2O4)[C...,InChI=1S/C12H8Cl6O/c13-8-9(14)11(16)5-3-1-2(6-...,DFBKLUNHFCTMDC-PICURKEMSA-N
21,Rotenone,6758,"(1S,6R,13S)-16,17-dimethoxy-6-prop-1-en-2-yl-2...",C23H22O6,394.4,CC(=C)[C@H]1CC2=C(O1)C=CC3=C2O[C@@H]4COC5=CC(=...,InChI=1S/C23H22O6/c1-11(2)16-8-14-15(28-16)6-5...,JUVIOZPCNVVQFO-HBGVWJBISA-N
22,Sulfaclozine,66890,4-amino-N-(6-chloropyrazin-2-yl)benzenesulfona...,C10H9ClN4O2S,284.72,C1=CC(=CC=C1N)S(=O)(=O)NC2=CN=CC(=N2)Cl,InChI=1S/C10H9ClN4O2S/c11-9-5-13-6-10(14-9)15-...,QKLPUVXBJHRFQZ-UHFFFAOYSA-N
23,ethanal,177,acetaldehyde,C2H4O,44.05,CC=O,"InChI=1S/C2H4O/c1-2-3/h2H,1H3",IKHGUXGNUITLKF-UHFFFAOYSA-N
24,2-pyrrolidone,12025,pyrrolidin-2-one,C4H7NO,85.10,C1CC(=O)NC1,"InChI=1S/C4H7NO/c6-4-2-1-3-5-4/h1-3H2,(H,5,6)",HNJBEVLQSNELDL-UHFFFAOYSA-N
25,2-Chloronaphthalene,7056,2-chloronaphthalene,C10H7Cl,162.61,C1=CC=C2C=C(C=CC2=C1)Cl,InChI=1S/C10H7Cl/c11-10-6-5-8-3-1-2-4-9(8)7-10...,CGYGETOMCSJHJU-UHFFFAOYSA-N
26,Primidone,4909,"5-ethyl-5-phenyl-1,3-diazinane-4,6-dione",C12H14N2O2,218.25,CCC1(C(=O)NCNC1=O)C2=CC=CC=C2,InChI=1S/C12H14N2O2/c1-2-12(9-6-4-3-5-7-9)10(1...,DQMZLTXERSFNPB-UHFFFAOYSA-N
27,2-Chloropropane,6361,2-chloropropane,C3H7Cl,78.54,CC(C)Cl,"InChI=1S/C3H7Cl/c1-3(2)4/h3H,1-2H3",ULYZAYCEDJDHCC-UHFFFAOYSA-N
28,Doxylamine,3162,"N,N-dimethyl-2-(1-phenyl-1-pyridin-2-ylethoxy)...",C17H22N2O,270.37,CC(C1=CC=CC=C1)(C2=CC=CC=N2)OCCN(C)C,"InChI=1S/C17H22N2O/c1-17(20-14-13-19(2)3,15-9-...",HCFDWZZGGLSKEP-UHFFFAOYSA-N
29,"6,7-Dihydropteridine",167,"6,7-dihydropteridine",C6H6N4,134.14,C1CN=C2C(=N1)C=NC=N2,InChI=1S/C6H6N4/c1-2-9-6-5(8-1)3-7-4-10-6/h3-4...,KVDQMARGGBLIJM-UHFFFAOYSA-N
30,Benzonitrile,7505,benzonitrile,C7H5N,103.12,C1=CC=C(C=C1)C#N,InChI=1S/C7H5N/c8-6-7-4-2-1-3-5-7/h1-5H,JFDZBHWFFUWGJE-UHFFFAOYSA-N
31,Diazinon,3017,diethoxy-(6-methyl-2-propan-2-ylpyrimidin-4-yl...,C12H21N2O3PS,304.35,CCOP(=S)(OCC)OC1=NC(=NC(=C1)C)C(C)C,"InChI=1S/C12H21N2O3PS/c1-6-15-18(19,16-7-2)17-...",FHIVAFMUCKRCQO-UHFFFAOYSA-N
32,Acetorphine hydrochloride,71587068,"[(1R,2S,6R,14R,15R,19R)-19-[(2R)-2-hydroxypent...",C27H36ClNO5,490.0,CCC[C@](C)([C@H]1C[C@@]23C=C[C@@]1([C@H]4[C@@]...,"InChI=1S/C27H35NO5.ClH/c1-6-9-24(3,30)19-15-25...",NDKZQFXDYCJPKG-PXCSINNHSA-N
33,Diethyl Ether,3283,ethoxyethane,C4H10O,74.12,CCOCC,"InChI=1S/C4H10O/c1-3-5-4-2/h3-4H2,1-2H3",RTZKZFJDLAIYFH-UHFFFAOYSA-N
34,5-Hydroxytryptophan,144,2-amino-3-(5-hydroxy-1H-indol-3-yl)propanoic acid,C11H12N2O3,220.22,C1=CC2=C(C=C1O)C(=CN2)CC(C(=O)O)N,InChI=1S/C11H12N2O3/c12-9(11(15)16)3-6-5-13-10...,LDCYZAJDBXYCGN-UHFFFAOYSA-N
35,Warfarin,54678486,4-hydroxy-3-(3-oxo-1-phenylbutyl)chromen-2-one,C19H16O4,308.3,CC(=O)CC(C1=CC=CC=C1)C2=C(C3=CC=CC=C3OC2=O)O,InChI=1S/C19H16O4/c1-12(20)11-15(13-7-3-2-4-8-...,PJVWKTKQMONHTI-UHFFFAOYSA-N
36,Atropine,174174,"[(1R,5S)-8-methyl-8-azabicyclo[3.2.1]octan-3-y...",C17H23NO3,289.4,CN1[C@@H]2CC[C@H]1CC(C2)OC(=O)C(CO)C3=CC=CC=C3,InChI=1S/C17H23NO3/c1-18-13-7-8-14(18)10-15(9-...,RKUNBYITZUJHSG-PJPHBNEVSA-N
37,Chloramphenicol,5959,"2,2-dichloro-N-[(1R,2R)-1,3-dihydroxy-1-(4-nit...",C11H12Cl2N2O5,323.13,C1=CC(=CC=C1[C@H]([C@@H](CO)NC(=O)C(Cl)Cl)O)[N...,InChI=1S/C11H12Cl2N2O5/c12-10(13)11(18)14-8(5-...,WIIZWVCIJKGZOK-RKDXNWHRSA-N
38,Lansoprazole,3883,"2-[[3-methyl-4-(2,2,2-trifluoroethoxy)pyridin-...",C16H14F3N3O2S,369.4,CC1=C(C=CN=C1CS(=O)C2=NC3=CC=CC=C3N2)OCC(F)(F)F,InChI=1S/C16H14F3N3O2S/c1-10-13(20-7-6-14(10)2...,MJIHNNLFOKEZEW-UHFFFAOYSA-N
39,Acetorphine,20055090,"[(1R,2S,6R,14R,15R,19R)-19-[(2R)-2-hydroxypent...",C27H35NO5,453.6,CCC[C@](C)([C@H]1C[C@@]23C=C[C@@]1([C@H]4[C@@]...,"InChI=1S/C27H35NO5/c1-6-9-24(3,30)19-15-25-10-...",LFYBMMHFJIAKFE-PMEKXCSPSA-N
40,3-Chloroalanine,78,2-amino-3-chloropropanoic acid,C3H6ClNO2,123.54,C(C(C(=O)O)N)Cl,"InChI=1S/C3H6ClNO2/c4-1-2(5)3(6)7/h2H,1,5H2,(H...",ASBJGPTTYPEMLP-UHFFFAOYSA-N
41,Methylnaltrexone,5361918,"(4R,4aS,7aR,12bS)-3-(cyclopropylmethyl)-4a,9-d...",C21H26NO4+,356.4,C[N+]1(CC[C@]23[C@@H]4C(=O)CC[C@]2([C@H]1CC5=C...,InChI=1S/C21H25NO4/c1-22(11-12-2-3-12)9-8-20-1...,JVLBPIPGETUEET-GAAHOAFPSA-O
42,Buprenorphine,644073,"(1S,2S,6R,14R,15R,16R)-5-(cyclopropylmethyl)-1...",C29H41NO4,467.6,C[C@]([C@H]1C[C@@]23CC[C@@]1([C@H]4[C@@]25CCN(...,"InChI=1S/C29H41NO4/c1-25(2,3)26(4,32)20-15-27-...",RMRJXGBAOAMLHD-IHFGGWKQSA-N
43,Nalorphine,5284595,"(4R,4aR,7S,7aR,12bS)-3-prop-2-enyl-2,4,4a,7,7a...",C19H21NO3,311.4,C=CCN1CC[C@]23[C@@H]4[C@H]1CC5=C2C(=C(C=C5)O)O...,InChI=1S/C19H21NO3/c1-2-8-20-9-7-19-12-4-6-15(...,UIQMVEYFGZJHCZ-SSTWWWIQSA-N

In [13]:
df.to_csv("pubchem_molecules.csv")

In [14]:
df2 = df[["Name","SMILES"]]
df2

,Name,SMILES
0,methane,C
1,2-acetyloxybenzoic acid,CC(=O)OC1=CC=CC=C1C(=O)O
2,pentanal,CCCCC=O
3,aspirin,CC(=O)OC1=CC=CC=C1C(=O)O
4,ibuprofen,CC(C)CC1=CC=C(C=C1)C(C)C(=O)O
5,paracetamol,CC(=O)NC1=CC=C(C=C1)O
6,naproxen,C[C@@H](C1=CC2=C(C=C1)C=C(C=C2)OC)C(=O)O
7,diclofenac,C1=CC=C(C(=C1)CC(=O)O)NC2=C(C=CC=C2Cl)Cl
8,codeine,CN1CC[C@]23[C@@H]4[C@H]1CC5=C2C(=C(C=C5)OC)O[C...
9,ethanol,CCO
10,methamphetamine,C[C@@H](CC1=CC=CC=C1)NC
11,morphine,CN1CC[C@]23[C@@H]4[C@H]1CC5=C2C(=C(C=C5)O)O[C@...
12,caprolactam,C1CCC(=O)NCC1
13,Amygdalin,C1=CC=C(C=C1)[C@H](C#N)O[C@H]2[C@@H]([C@H]([C@...
14,Fenfuram,CC1=C(C=CO1)C(=O)NC2=CC=CC=C2
15,citral,CC(=CCC/C(=C/C=O)/C)C
16,Zearalenone,C[C@H]1CCCC(=O)CCC/C=C/C2=C(C(=CC(=C2)O)O)C(=O)O1
17,Picene,C1=CC=C2C(=C1)C=CC3=C2C=CC4=C3C=CC5=CC=CC=C54
18,"2,2',4,6,6'-Pentachlorobiphenyl",C1=CC(=C(C(=C1)Cl)C2=C(C=C(C=C2Cl)Cl)Cl)Cl
19,Estradiol,C[C@]12CC[C@H]3[C@H]([C@@H]1CC[C@@H]2O)CCC4=C3...
20,Dieldrin,C1[C@@H]2[C@H]3[C@@H]([C@H]1[C@H]4[C@@H]2O4)[C...
21,Rotenone,CC(=C)[C@H]1CC2=C(O1)C=CC3=C2O[C@@H]4COC5=CC(=...
22,Sulfaclozine,C1=CC(=CC=C1N)S(=O)(=O)NC2=CN=CC(=N2)Cl
23,ethanal,CC=O
24,2-pyrrolidone,C1CC(=O)NC1
25,2-Chloronaphthalene,C1=CC=C2C=C(C=CC2=C1)Cl
26,Primidone,CCC1(C(=O)NCNC1=O)C2=CC=CC=C2
27,2-Chloropropane,CC(C)Cl
28,Doxylamine,CC(C1=CC=CC=C1)(C2=CC=CC=N2)OCCN(C)C
29,"6,7-Dihydropteridine",C1CN=C2C(=N1)C=NC=N2
30,Benzonitrile,C1=CC=C(C=C1)C#N
31,Diazinon,CCOP(=S)(OCC)OC1=NC(=NC(=C1)C)C(C)C
32,Acetorphine hydrochloride,CCC[C@](C)([C@H]1C[C@@]23C=C[C@@]1([C@H]4[C@@]...
33,Diethyl Ether,CCOCC
34,5-Hydroxytryptophan,C1=CC2=C(C=C1O)C(=CN2)CC(C(=O)O)N
35,Warfarin,CC(=O)CC(C1=CC=CC=C1)C2=C(C3=CC=CC=C3OC2=O)O
36,Atropine,CN1[C@@H]2CC[C@H]1CC(C2)OC(=O)C(CO)C3=CC=CC=C3
37,Chloramphenicol,C1=CC(=CC=C1[C@H]([C@@H](CO)NC(=O)C(Cl)Cl)O)[N...
38,Lansoprazole,CC1=C(C=CN=C1CS(=O)C2=NC3=CC=CC=C3N2)OCC(F)(F)F
39,Acetorphine,CCC[C@](C)([C@H]1C[C@@]23C=C[C@@]1([C@H]4[C@@]...
40,3-Chloroalanine,C(C(C(=O)O)N)Cl
41,Methylnaltrexone,C[N+]1(CC[C@]23[C@@H]4C(=O)CC[C@]2([C@H]1CC5=C...
42,Buprenorphine,C[C@]([C@H]1C[C@@]23CC[C@@]1([C@H]4[C@@]25CCN(...
43,Nalorphine,C=CCN1CC[C@]23[C@@H]4[C@H]1CC5=C2C(=C(C=C5)O)O...

In [15]:
df2.to_csv("pubchem_mol_smiles.csv")

_______

#### Another Method

In [20]:
cid = []
for name in molecules:
    compound = pcp.get_compounds(name, "name")[0]
    cid.append(compound.cid)
cid

[297,
 2244,
 8063,
 2244,
 3672,
 1983,
 156391,
 3033,
 5284371,
 702,
 10836,
 5288826,
 7768,
 656516,
 90590,
 638011,
 5281576,
 9162,
 91662,
 5757,
 969491,
 6758,
 66890,
 177,
 12025,
 7056,
 4909,
 6361,
 3162,
 167,
 7505,
 3017,
 71587068,
 3283,
 144,
 54678486,
 174174,
 5959,
 3883,
 20055090,
 78,
 5361918,
 644073,
 5284595]

##### The available properties are:

"IUPACName,MolecularFormula,MolecularWeight,CanonicalSMILES,IsomericSMILES,InChI,InChIKey,XLogP,ExactMass,MonoisotopicMass,TPSA,Complexity,Charge,HBondDonorCount,HBondAcceptorCount,RotatableBondCount,HeavyAtomCount,IsotopeAtomCount,AtomStereoCount,DefinedAtomStereoCount,UndefinedAtomStereoCount,CovalentUnitCount,Volume3D,ConformerCount3D"

In [21]:
pcp.download("CSV", "pubchem_molecules_full.csv", cid, operation="property/IUPACName,MolecularFormula,MolecularWeight,CanonicalSMILES,IsomericSMILES,InChI,InChIKey,XLogP,ExactMass,MonoisotopicMass,TPSA,Complexity,Charge,HBondDonorCount,HBondAcceptorCount,RotatableBondCount,HeavyAtomCount,IsotopeAtomCount,AtomStereoCount,DefinedAtomStereoCount,UndefinedAtomStereoCount,CovalentUnitCount,Volume3D,ConformerCount3D")